FROM quay.io/centos/centos:stream10

ARG FOREMAN_VERSION=nightly
ARG KATELLO_VERSION=nightly
ARG FOREMAN_UID=994
ARG FOREMAN_GID=994

ENV RAILS_ENV=production
ENV RAILS_LOG_TO_STDOUT=true

RUN groupadd -r -g ${FOREMAN_GID} foreman && \
    useradd -r -g foreman -u ${FOREMAN_UID} -d /usr/share/foreman -s /sbin/nologin -c "Foreman user" foreman

RUN dnf upgrade -y && dnf install --nodocs -y https://yum.theforeman.org/releases/${FOREMAN_VERSION}/el10/x86_64/foreman-release.rpm https://yum.theforeman.org/katello/${KATELLO_VERSION}/katello/el10/x86_64/katello-repos-latest.rpm && \
    dnf install foreman foreman-postgresql foreman-service foreman-redis foreman-dynflow-sidekiq \
        foreman-libvirt foreman-vmware foreman-openstack foreman-ec2 --nodocs -y && \
    dnf clean all
WORKDIR /usr/share/foreman
ENV MALLOC_ARENA_MAX=2
ENV FOREMAN_BIND=0.0.0.0
ENV RAILS_SERVE_STATIC_FILES=true
CMD /usr/share/foreman/bin/rails db:migrate && /usr/share/foreman/bin/rails db:seed && /usr/share/foreman/bin/rails server --environment production --pid /tmp/rails.pid
EXPOSE 3000/tcp

ARG FOREMAN_PLUGINS="foreman-tasks foreman_remote_execution katello foreman_google foreman_azure_rm foreman_kubevirt foreman_rh_cloud foreman_ansible foreman_webhooks"

RUN set -eu; for PLUGIN in ${FOREMAN_PLUGINS}; do \
    echo $PLUGIN; \
    dnf install --nodocs -y "rubygem($PLUGIN)"; \
    echo "gem '$PLUGIN' if ENV.fetch('FOREMAN_ENABLED_PLUGINS', '').split.include?('$PLUGIN') || ENV.fetch('FOREMAN_ENABLED_PLUGINS', nil).nil?" > /usr/share/foreman/bundler.d/$PLUGIN.rb; \
  done; dnf clean all

RUN dnf install -y 'dnf*-command(copr)' && \
    dnf copr enable -y packit/Katello-katello-11835 rhel-10-x86_64 && \
    dnf install -y rubygem-katello-doc-5.1.0-0.1.pre.master.20260818223249926209.pr11835.6050.g3d8b356a87.el10.noarch \
        rubygem-katello-assets-5.1.0-0.1.pre.master.20260818223249926209.pr11835.6050.g3d8b356a87.el10.noarch \
        rubygem-katello-5.1.0-0.1.pre.master.20260818223249926209.pr11835.6050.g3d8b356a87.el10.noarch

RUN rm /usr/share/foreman/config/initializers/encryption_key.rb /etc/foreman/encryption_key.rb

USER foreman
