FROM quay.io/centos/centos:stream10

ARG FOREMAN_VERSION=nightly
ARG KATELLO_VERSION=nightly
ARG FOREMAN_PROXY_PLUGINS=""

RUN dnf upgrade -y && dnf copr enable ekohl/foreman-nightly-staging rhel-10-x86_64 -y && \
	dnf install --nodocs foreman-proxy openssh-clients openssh -y && dnf clean all

RUN set -eu; for PLUGIN in ${FOREMAN_PROXY_PLUGINS}; do \
    echo $PLUGIN; \
    dnf install --nodocs -y "foreman-proxy-plugin-$PLUGIN"; \
    echo "gem 'smart_proxy_$PLUGIN' if ENV.fetch('FOREMAN_PROXY_ENABLED_PLUGINS', '').split.include?('$PLUGIN') || ENV.fetch('FOREMAN_PROXY_ENABLED_PLUGINS', nil).nil?" > /usr/share/foreman-proxy/bundler.d/$PLUGIN.rb; \
  done; dnf clean all

RUN sed -i 's/:enabled:.*/:enabled: false/g' /etc/foreman-proxy/settings.d/*.yml

USER foreman-proxy
WORKDIR /usr/share/foreman-proxy
ENV MALLOC_ARENA_MAX=2
CMD /usr/share/foreman-proxy/bin/smart-proxy
EXPOSE 8443/tcp
